title: "@box2d"
description: A full-blown ecosystem for box2d for the JavaScript/TypeScript world
base: "/box2d.ts/docs/"
themeConfig:
  sidebarDepth: 0
  nav:
  - link: "/guide/"
    text: Guide
  - link: "https://lusito.github.io/box2d.ts/benchmark/"
    text: Benchmarks
  - link: "https://lusito.github.io/box2d.ts/testbed/"
    text: Demos
  - link: https://github.com/lusito/box2d.ts
    text: Github
  sidebar:
    "/guide/":
    - title: Getting Started
      children:
      - ''
    - title: Box2D
      children:
      - core/
      - core/key-differences
    - title: Debug Draw
      children:
      - debug-draw/
    - title: Lights
      children:
      - lights/
      - lights/getting-started
      - lights/glossary
      - lights/custom-viewport
      - lights/performance-tuning
    - title: Particles
      children:
      - particles/
    - title: Controllers
      children:
      - controllers/
  displayAllHeaders: true
plugins:
- fulltext-search
