name: Documentation
on:
  push:
    branches: [master]
jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: volta-cli/action@v4
      - name: Install
        run: npm ci
      - name: Build Testbed
        run: npm run docs:build:testbed
      - name: Build Benchmark
        run: npm run docs:build:benchmark
      - name: Build Docs
        run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
